### ISSUE TITLE
Reference files from reference project

### ISSUE THREAD

**Issue by sophie22** [eastgenomics/eggd_conductor_configs#17]
Somalier_extract stage reference genome related files should be taken from 001_Reference project:
https://github.com/eastgenomics/eggd_conductor_configs/blob/main/assay_configs/CEN/eggd_conductor_dias_CEN_config_v1.1.0.json#L87

project ID should be updated to `project-Fkb6Gkj433GVVvj73J7x8KbV` or `project-F3zqGV04fXX5j7566869fjFq`

**Comment by chrispyatt** [comment]
fixed by #22 & #24
