### ISSUE TITLE
Update MultiQC instance for CEN config

### ISSUE THREAD

**Issue by Addy81** [eastgenomics/eggd_conductor_configs#21]
If S1 becomes routine, MultiQC fails with the default instance, to be updated to match the TWE one
`
"systemRequirements": {"*": {"instanceType": "mem1_ssd1_v2_x8"}}`

**Comment by jethror1** [comment]
Closing as completed in 1.2: https://github.com/eastgenomics/eggd_conductor_configs/blob/626c58f7225a19fc62bacd73c9deb3dc0e744068/assay_configs/CEN/eggd_conductor_dias_CEN_config_v1.2.0.json#L229
